# Generated by Django 5.0.3 on 2024-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('deviceType', models.CharField(max_length=50)),
                ('serialNumber', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('CPU', models.CharField(max_length=50)),
                ('GPU', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
