# Generated by Django 5.0.4 on 2024-04-30 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('device_serial', models.CharField(blank=True, max_length=50)),
                ('CPU', models.CharField(blank=True, max_length=50)),
                ('GPU', models.CharField(blank=True, max_length=10)),
                ('RAM', models.CharField(blank=True, max_length=5)),
                ('quantity', models.IntegerField()),
                ('audit', models.DateField(null=True)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Decommisioned', 'Decommisioned'), ('On Loan', 'On Loan'), ('Repairing', 'Repairing')], default='Available', max_length=13)),
                ('image', models.ImageField(upload_to='inventories/media/images')),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Reserved', 'Reserved')], default='Active', max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.item')),
            ],
        ),
    ]
