# Generated by Django 5.0.4 on 2024-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ram',
        ),
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='device_serial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='CPU',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='GPU',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='RAM',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
