# Generated by Django 5.0.4 on 2024-04-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_remove_item_cpu_remove_item_gpu_remove_item_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='audit',
            field=models.DateField(null=True),
        ),
    ]
