# Generated by Django 5.0.3 on 2024-04-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_rename_date_booking_start_date_booking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=42, upload_to='inventories/media/images'),
            preserve_default=False,
        ),
    ]
