# Generated by Django 5.0.3 on 2024-04-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_rename_date_booking_start_date_booking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='inventories/media/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
