# Generated by Django 5.0.3 on 2024-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
