# Generated by Django 5.0.3 on 2024-04-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_item_image_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventories/media/images'),
        ),
    ]
